version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: karka
      MYSQL_DATABASE: moviedatabase
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - db
    ports:
      - "8081:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: karka
      MYSQL_HOST: db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:90"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/moviedatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: karka
